FROM morlov/tippecanoe

LABEL maintainer="Mikhail Orlov <miklergm@gmail.com>"

FROM morlov/mbtiles-server

COPY --from=0 /usr/bin/tippe* /usr/local/bin/
COPY --from=0 /usr/bin/tile* /usr/local/bin/

RUN apk add --no-cache libgcc libstdc++ sqlite-libs postgresql-client

# Enables customized options using environment variables
# Can be used for tippecanoe output
ENV ZOOM='8'

ENV MBTILES_SERVER_WATCH=true